name: Code Style Testing
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==22.10.0 pylint==2.15.5 isort==5.10.1
      - name: Black Formatting test
        run: black --config=pyproject.toml redpandas
      - name: Pylint Style test
        run: Pylint --rcfile=pyproject.toml redpandas
      - name: isort imports test
        run: isort redpandas